//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorErrorCode.
const (
	Internal            ErrorErrorCode = "internal"
	InvalidRequest      ErrorErrorCode = "invalid_request"
	NoData              ErrorErrorCode = "no_data"
	NotFound            ErrorErrorCode = "not_found"
	UnsupportedCurrency ErrorErrorCode = "unsupported_currency"
	UpstreamUnavailable ErrorErrorCode = "upstream_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case Internal:
		return true
	case InvalidRequest:
		return true
	case NoData:
		return true
	case NotFound:
		return true
	case UnsupportedCurrency:
		return true
	case UpstreamUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusDoneStatus.
const (
	Done JobStatusDoneStatus = "done"
)

// Valid indicates whether the value is a known member of the JobStatusDoneStatus enum.
func (e JobStatusDoneStatus) Valid() bool {
	switch e {
	case Done:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusFailedStatus.
const (
	Failed JobStatusFailedStatus = "failed"
)

// Valid indicates whether the value is a known member of the JobStatusFailedStatus enum.
func (e JobStatusFailedStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusPendingStatus.
const (
	Pending JobStatusPendingStatus = "pending"
)

// Valid indicates whether the value is a known member of the JobStatusPendingStatus enum.
func (e JobStatusPendingStatus) Valid() bool {
	switch e {
	case Pending:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    ErrorErrorCode `json:"code"`
		Message string         `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode defines model for Error.Error.Code.
type ErrorErrorCode string

// JobStatus defines model for JobStatus.
type JobStatus struct {
	union json.RawMessage
}

// JobStatusDone defines model for JobStatusDone.
type JobStatusDone struct {
	Base        string              `json:"base"`
	CompletedAt time.Time           `json:"completed_at"`
	CreatedAt   time.Time           `json:"created_at"`
	Id          openapi_types.UUID  `json:"id"`
	Price       float64             `json:"price"`
	Quote       string              `json:"quote"`
	Status      JobStatusDoneStatus `json:"status"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// JobStatusDoneStatus defines model for JobStatusDone.Status.
type JobStatusDoneStatus string

// JobStatusFailed defines model for JobStatusFailed.
type JobStatusFailed struct {
	Attempts    int       `json:"attempts"`
	Base        string    `json:"base"`
	CompletedAt time.Time `json:"completed_at"`
	CreatedAt   time.Time `json:"created_at"`
	Error       struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
	Id     openapi_types.UUID    `json:"id"`
	Quote  string                `json:"quote"`
	Status JobStatusFailedStatus `json:"status"`
}

// JobStatusFailedStatus defines model for JobStatusFailed.Status.
type JobStatusFailedStatus string

// JobStatusPending defines model for JobStatusPending.
type JobStatusPending struct {
	Attempts  int                    `json:"attempts"`
	Base      string                 `json:"base"`
	CreatedAt time.Time              `json:"created_at"`
	Id        openapi_types.UUID     `json:"id"`
	Quote     string                 `json:"quote"`
	Status    JobStatusPendingStatus `json:"status"`
}

// JobStatusPendingStatus defines model for JobStatusPending.Status.
type JobStatusPendingStatus string

// LatestQuote defines model for LatestQuote.
type LatestQuote struct {
	Base      string    `json:"base"`
	Price     float64   `json:"price"`
	Quote     string    `json:"quote"`
	UpdatedAt time.Time `json:"updated_at"`
}

// RefreshAccepted defines model for RefreshAccepted.
type RefreshAccepted struct {
	Id openapi_types.UUID `json:"id"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	Base  string `json:"base"`
	Quote string `json:"quote"`
}

// GetLatestQuoteParams defines parameters for GetLatestQuote.
type GetLatestQuoteParams struct {
	Base        string  `form:"base" json:"base"`
	Quote       string  `form:"quote" json:"quote"`
	XRequestId  *string `json:"X-Request-Id,omitempty"`
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// RefreshQuoteParams defines parameters for RefreshQuote.
type RefreshQuoteParams struct {
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetQuoteJobParams defines parameters for GetQuoteJob.
type GetQuoteJobParams struct {
	XRequestId  *string `json:"X-Request-Id,omitempty"`
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// RefreshQuoteJSONRequestBody defines body for RefreshQuote for application/json ContentType.
type RefreshQuoteJSONRequestBody = RefreshRequest

// AsJobStatusPending returns the union data inside the JobStatus as a JobStatusPending
func (t JobStatus) AsJobStatusPending() (JobStatusPending, error) {
	var body JobStatusPending
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusPending overwrites any union data inside the JobStatus as the provided JobStatusPending
func (t *JobStatus) FromJobStatusPending(v JobStatusPending) error {
	v.Status = "pending"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusPending performs a merge with any union data inside the JobStatus, using the provided JobStatusPending
func (t *JobStatus) MergeJobStatusPending(v JobStatusPending) error {
	v.Status = "pending"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobStatusDone returns the union data inside the JobStatus as a JobStatusDone
func (t JobStatus) AsJobStatusDone() (JobStatusDone, error) {
	var body JobStatusDone
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusDone overwrites any union data inside the JobStatus as the provided JobStatusDone
func (t *JobStatus) FromJobStatusDone(v JobStatusDone) error {
	v.Status = "done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusDone performs a merge with any union data inside the JobStatus, using the provided JobStatusDone
func (t *JobStatus) MergeJobStatusDone(v JobStatusDone) error {
	v.Status = "done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobStatusFailed returns the union data inside the JobStatus as a JobStatusFailed
func (t JobStatus) AsJobStatusFailed() (JobStatusFailed, error) {
	var body JobStatusFailed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusFailed overwrites any union data inside the JobStatus as the provided JobStatusFailed
func (t *JobStatus) FromJobStatusFailed(v JobStatusFailed) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusFailed performs a merge with any union data inside the JobStatus, using the provided JobStatusFailed
func (t *JobStatus) MergeJobStatusFailed(v JobStatusFailed) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JobStatus) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t JobStatus) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "done":
		return t.AsJobStatusDone()
	case "failed":
		return t.AsJobStatusFailed()
	case "pending":
		return t.AsJobStatusPending()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t JobStatus) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JobStatus) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the last successful quote for a currency pair
	// (GET /quotes/latest)
	GetLatestQuote(w http.ResponseWriter, r *http.Request, params GetLatestQuoteParams)
	// Trigger a background currency-rate fetch
	// (POST /quotes/refresh)
	RefreshQuote(w http.ResponseWriter, r *http.Request, params RefreshQuoteParams)
	// Return the state of one refresh job
	// (GET /quotes/{id})
	GetQuoteJob(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetQuoteJobParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLatestQuote operation middleware
func (siw *ServerInterfaceWrapper) GetLatestQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestQuoteParams

	// ------------- Required query parameter "base" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "base", r.URL.Query(), &params.Base, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "base"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "base", Err: err})
		}
		return
	}

	// ------------- Required query parameter "quote" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "quote", r.URL.Query(), &params.Quote, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "quote"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quote", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshQuote operation middleware
func (siw *ServerInterfaceWrapper) RefreshQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshQuoteParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuoteJob operation middleware
func (siw *ServerInterfaceWrapper) GetQuoteJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuoteJobParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuoteJob(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quotes/latest", wrapper.GetLatestQuote)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/quotes/refresh", wrapper.RefreshQuote)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quotes/{id}", wrapper.GetQuoteJob)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FnrbhPJEn6VUh8kQBo7JgnonPArhByUCEI2EIldyEbt7hq7szPdk74kWJGlfYh9wn2SVfXMeHyL7bAO",
	"rFj4QazpmrrXV1U9N0yYvDAatXds54Y50cecx5/71hpLPwprCrReYXyM8x8LIzEe65CznY9M6SueKXlu",
	"8TKg8yxhQbtQFMZ6lOciWItaDFjCtDmX3PP4y5+nJmhJxIXzFnl+HjS/4irj3QxZwpT2aDXP2FnC/KBA",
	"tsOct0r32DBhOTrHe6UWn3leZHRcS4KHh8c/PwTlQBsPI03YDJ9hwkhnZVGSHdGuhncj13QvUPgZ+tI9",
	"s2QJOzTdd577EN0llRNW5UpzX3oz50VB8unMaHrzPxtNaDaquGyMmLwkooSlXGUkeAn1/0uyhBWoZRSz",
	"5IXjim6Y1HEeHPG89FO0YZgwo/FtynY+3rAHFtM7sFzxhWjiytSVicOzcVdHFjO52uUuPp3JIOKfISUo",
	"90SQGpvTLya5x5ZXObI5eScs8ru+o+QEbQhKziMrrBI4ydWEshQqWh3yLlqivQzGzzfLjdKurs6YYvNq",
	"KBTyjrZM5X+0Izq41mgkf8JTU86uTZ3QYGEVVfGeCS73HvOiRLNcaZWTxZ0RJ0KQXumwf0AaLAHTRRD3",
	"N2Fr5RS8S1pVaHR2b0kyCm6yCtDWiHMvOXJ/RX8Xj9d4vkaXj5wzz7evuUfnf6o1nI+rTffdPz1ZCGsj",
	"ys1Oe/Pp02fb/03uBHWNpDcfjth94NmUy1ZEqRNMLbr+rhBY+HkoVaZCo/7/us/wSbrFW51OpzP1X/2P",
	"JctyZzbmC5Q7qSazlcNYUGZYzXbYrx93W7+c3WwNHyzM3+norMZgUQDmjF9UVzo1cXBCGqoKrwzJ2HUD",
	"LfrWaBMcjMbAyAcc2islsA17maJxArxVvR5a4GBL78CV4p/08dt372EjvuM2qpMECpNlkBoLvo9g0YXM",
	"Ezm82m+Ib5QcJsC1/KQtchlJs1g8ILjoo6w0mX6vpGl/0uQY5aP39mrlY93Bu1J5lrArtK40ttN+0u7E",
	"oaxAzQvFdthWu9PeKr3ej3GdFEFPehj/UPA5ee2AJslX6MernBhYnqNH6+Kwp0jeZUAbp/dyKKyC1MTN",
	"24BJtU3EDFsx9PPZ19W3Nv595BJtI+BDq6qG1gGVVcN3VQYHaevIaGy94V70F3I4IzNcYbQrq22z0ylb",
	"vvaoYzh4UWRKxIBsXDgK780Yv0XD8HjcYmVMVkR5DC4Igc6lIatysEnl6AOUUHBl2yypzIx67lHWtvaM",
	"9tZks9V2HLqZEjG3le6BVBaFV1cI18r3IeefW7yHgJeBZ+ANCMMzdIJIr5WW5rq92O1s/z3vzUrd1175",
	"AXjei0YIo6WiI57FoqrWvGW8J6I/4expWqLe6mzPKnJkPLwxUqUKJfz5+x9A+kJO2YDyOWgDXSMHYNEH",
	"q1FO+XYl4yhCFXRYdCZYges1bHuNmVheHszJwRdc1nkW/TR2KzAC6QSq2wMo+10CxoLDLG2tkpfrdMj2",
	"/TvkyMwWJH5WzjsYoK8irxx8XdOffo1cOKhuc2I7RgtxpP9aNtI4HfKc2wHbYSexLqsmfRtE8maKoGBE",
	"iVOzQWxFxs3pqtXQtainfnFTOis7Izr/wsjB2uI2NScOJycz6sDDmV62uW7poxF6Tv4cmi7w6pxGLZDB",
	"8m42ANSXAcMMzC5pYfF4rHONTXjRxGVo+9qUhs5yPj15DSaNzDReZwOoFi64MN0vBvNJEdUZCGMtZlEP",
	"UBK1p5ZkF/P+ZuBfwzyV0wjr53eEb9MB/mUw+H60BXW5+K1nTdBNDFqWExAiDbjj0EebzqJlIkLeoene",
	"gnq0njSYF7fa28f8pfvv9z3fN58QbkHD+PnkeT1rphkKX+++HsrrHnhU3RklII3GWFnlvd3ju8Pl5KjP",
	"i8Kawio+tlMQwpWC1zLhe7S5oloZ+RgekRlTViySc4LeDlq7qUc7D0aFyXPUkpYgk2VkYPzodMUzUBoc",
	"0o7ROBGMzgaPv8WCMb3r/Ng1lrcbWX//41A2ntPTg5ff2T5BMEAmRij40Snvf2EgdEMa7wiG6tvDC9ON",
	"L/0VAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
