//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorErrorCode.
const (
	Internal            ErrorErrorCode = "internal"
	InvalidRequest      ErrorErrorCode = "invalid_request"
	NoData              ErrorErrorCode = "no_data"
	NotFound            ErrorErrorCode = "not_found"
	UnsupportedCurrency ErrorErrorCode = "unsupported_currency"
	UpstreamUnavailable ErrorErrorCode = "upstream_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case Internal:
		return true
	case InvalidRequest:
		return true
	case NoData:
		return true
	case NotFound:
		return true
	case UnsupportedCurrency:
		return true
	case UpstreamUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusDoneStatus.
const (
	Done JobStatusDoneStatus = "done"
)

// Valid indicates whether the value is a known member of the JobStatusDoneStatus enum.
func (e JobStatusDoneStatus) Valid() bool {
	switch e {
	case Done:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusFailedStatus.
const (
	Failed JobStatusFailedStatus = "failed"
)

// Valid indicates whether the value is a known member of the JobStatusFailedStatus enum.
func (e JobStatusFailedStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusPendingStatus.
const (
	Pending JobStatusPendingStatus = "pending"
)

// Valid indicates whether the value is a known member of the JobStatusPendingStatus enum.
func (e JobStatusPendingStatus) Valid() bool {
	switch e {
	case Pending:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    ErrorErrorCode `json:"code"`
		Message string         `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode defines model for Error.Error.Code.
type ErrorErrorCode string

// JobStatus defines model for JobStatus.
type JobStatus struct {
	union json.RawMessage
}

// JobStatusDone defines model for JobStatusDone.
type JobStatusDone struct {
	Base        string              `json:"base"`
	CompletedAt time.Time           `json:"completed_at"`
	CreatedAt   time.Time           `json:"created_at"`
	Id          openapi_types.UUID  `json:"id"`
	Price       float64             `json:"price"`
	Quote       string              `json:"quote"`
	Status      JobStatusDoneStatus `json:"status"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// JobStatusDoneStatus defines model for JobStatusDone.Status.
type JobStatusDoneStatus string

// JobStatusFailed defines model for JobStatusFailed.
type JobStatusFailed struct {
	Base        string    `json:"base"`
	CompletedAt time.Time `json:"completed_at"`
	CreatedAt   time.Time `json:"created_at"`
	Error       struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
	Id     openapi_types.UUID    `json:"id"`
	Quote  string                `json:"quote"`
	Status JobStatusFailedStatus `json:"status"`
}

// JobStatusFailedStatus defines model for JobStatusFailed.Status.
type JobStatusFailedStatus string

// JobStatusPending defines model for JobStatusPending.
type JobStatusPending struct {
	Base      string                 `json:"base"`
	CreatedAt time.Time              `json:"created_at"`
	Id        openapi_types.UUID     `json:"id"`
	Quote     string                 `json:"quote"`
	Status    JobStatusPendingStatus `json:"status"`
}

// JobStatusPendingStatus defines model for JobStatusPending.Status.
type JobStatusPendingStatus string

// LatestQuote defines model for LatestQuote.
type LatestQuote struct {
	Base      string    `json:"base"`
	Price     float64   `json:"price"`
	Quote     string    `json:"quote"`
	UpdatedAt time.Time `json:"updated_at"`
}

// RefreshAccepted defines model for RefreshAccepted.
type RefreshAccepted struct {
	Id openapi_types.UUID `json:"id"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	Base  string `json:"base"`
	Quote string `json:"quote"`
}

// GetLatestQuoteParams defines parameters for GetLatestQuote.
type GetLatestQuoteParams struct {
	Base        string  `form:"base" json:"base"`
	Quote       string  `form:"quote" json:"quote"`
	XRequestId  *string `json:"X-Request-Id,omitempty"`
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// RefreshQuoteParams defines parameters for RefreshQuote.
type RefreshQuoteParams struct {
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetQuoteJobParams defines parameters for GetQuoteJob.
type GetQuoteJobParams struct {
	XRequestId  *string `json:"X-Request-Id,omitempty"`
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// RefreshQuoteJSONRequestBody defines body for RefreshQuote for application/json ContentType.
type RefreshQuoteJSONRequestBody = RefreshRequest

// AsJobStatusPending returns the union data inside the JobStatus as a JobStatusPending
func (t JobStatus) AsJobStatusPending() (JobStatusPending, error) {
	var body JobStatusPending
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusPending overwrites any union data inside the JobStatus as the provided JobStatusPending
func (t *JobStatus) FromJobStatusPending(v JobStatusPending) error {
	v.Status = "pending"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusPending performs a merge with any union data inside the JobStatus, using the provided JobStatusPending
func (t *JobStatus) MergeJobStatusPending(v JobStatusPending) error {
	v.Status = "pending"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobStatusDone returns the union data inside the JobStatus as a JobStatusDone
func (t JobStatus) AsJobStatusDone() (JobStatusDone, error) {
	var body JobStatusDone
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusDone overwrites any union data inside the JobStatus as the provided JobStatusDone
func (t *JobStatus) FromJobStatusDone(v JobStatusDone) error {
	v.Status = "done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusDone performs a merge with any union data inside the JobStatus, using the provided JobStatusDone
func (t *JobStatus) MergeJobStatusDone(v JobStatusDone) error {
	v.Status = "done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobStatusFailed returns the union data inside the JobStatus as a JobStatusFailed
func (t JobStatus) AsJobStatusFailed() (JobStatusFailed, error) {
	var body JobStatusFailed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusFailed overwrites any union data inside the JobStatus as the provided JobStatusFailed
func (t *JobStatus) FromJobStatusFailed(v JobStatusFailed) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusFailed performs a merge with any union data inside the JobStatus, using the provided JobStatusFailed
func (t *JobStatus) MergeJobStatusFailed(v JobStatusFailed) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JobStatus) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t JobStatus) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "done":
		return t.AsJobStatusDone()
	case "failed":
		return t.AsJobStatusFailed()
	case "pending":
		return t.AsJobStatusPending()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t JobStatus) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JobStatus) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the last successful quote for a currency pair
	// (GET /quotes/latest)
	GetLatestQuote(w http.ResponseWriter, r *http.Request, params GetLatestQuoteParams)
	// Trigger a background currency-rate fetch
	// (POST /quotes/refresh)
	RefreshQuote(w http.ResponseWriter, r *http.Request, params RefreshQuoteParams)
	// Return the state of one refresh job
	// (GET /quotes/{id})
	GetQuoteJob(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetQuoteJobParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLatestQuote operation middleware
func (siw *ServerInterfaceWrapper) GetLatestQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestQuoteParams

	// ------------- Required query parameter "base" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "base", r.URL.Query(), &params.Base, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "base"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "base", Err: err})
		}
		return
	}

	// ------------- Required query parameter "quote" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "quote", r.URL.Query(), &params.Quote, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "quote"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quote", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshQuote operation middleware
func (siw *ServerInterfaceWrapper) RefreshQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshQuoteParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuoteJob operation middleware
func (siw *ServerInterfaceWrapper) GetQuoteJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuoteJobParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuoteJob(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quotes/latest", wrapper.GetLatestQuote)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/quotes/refresh", wrapper.RefreshQuote)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quotes/{id}", wrapper.GetQuoteJob)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FnrbhPJEn6VUh8kQBo7JgnonPArhByUCEI2EIldyEbt6Rq7szPdk744WJGlfYh9wn2SVfXMeHyZ+MI6",
	"sGLhB7HcNVVdt6++Gt+yWGe5VqicZXu3zMZ9zHj4eGiMNvQhNzpH4ySGr7H561gLDMfKZ2zvI5NqwFMp",
	"Lg1ee7SORcwr6/NcG4fiMvbGoIqHLGJKXwruePjkLhPtlSDh3DqDPLv0ig+4THk3RRYxqRwaxVN2ETE3",
	"zJHtMeuMVD02iliG1vJecYvPPMtTOq4swcPj058fgrSgtIPxTdicnlHE6M7SoCA/gl+17tqu7l5h7Obk",
	"i/DMi0XsWHffOe58CJeQNjYyk4q7IpoZz3OyT2da0ZP/2apTs1XmZWus5CUJRSzhMiXDS6T/X4hFLEcl",
	"gpklD5yWcqOoyvPwhGdFnIIPo4hphW8Ttvfxlj0wmKyhcsUHgosrS5cuji4mQx1UzNVql9vw7VwFkf4U",
	"qUC5I4FEm4w+McEdtpzMkDXUXWyQr/uMFFOy3kvRJJYbGeO0Vu2LVihllc+6aEj22mvX7JYdl13VnaHE",
	"mnrI52JNX2bqP/gRAlzdaGx/KlIzwa5cnbrBwi4q8/1PTO4SiFwEXH8TjFYurHWKpcSYi3tL/QqYWYHH",
	"Gum+v65cJ3gV4G4sek1hes0dWvdTda3mCNUz8fD8bCHYjCW3O+3tp0+f7f43WguAaktvPpyw+0CZmTit",
	"iB1nmBi0/f04xtw1YUeR//r6/+s+wyfJDm91Op3OzH/VPxYtK5j5RC+43FnJl1ZOY84dcSK2x379uN/6",
	"5eJ2Z/RgYdHOZmc1BYsS0ECKqJlUogOdQaI6uZOabOzboYr7RivtLYzJWdADFs1AxtiGg1TSkAdnZK+H",
	"BjiYIjowkPyTOn377j1shWfsVnkSQa7TFBJtwPURDFqfOhKHV4e18K0Uowi4Ep+UQS6CaBqaB2Ie91GU",
	"N5l9rpBpf1IUGOlC9A6qy4e+g3fF5VnEBmhs4Wyn/aTdCVQpR8VzyfbYTrvT3imi3g95nTZB3/Qw/KHk",
	"c4raEfG7V+gmu5wUGJ6hQ2MDBZNk79qjCZy6oGplkuq8OeMxKjl+qLAVU9+svuq+jenvIxdoagMfWmU3",
	"tI6orWq9qyo4SlonWmHrDXdxf6GGC3LD5lrZotu2O51iZCuHKqSD53kq45CQrStL6b2d0LeIok7mLXTG",
	"dEcUx2B9HKO1iU/LGqxLOcQABeRcmjaLSjfDPQ+oalsHWjmj0/luO/XdVMahtqXqgZAGYycHCDfS9SHj",
	"n1u8h4DXnqfgNMSap2hjEr2RSuib9uKws8P3vDdv9VA56YbgeC84EWslJB3xNDRVuXwt0z2V/algz8qS",
	"9E5nd/4iJ9rBGy1kIlHAn7//AXRfyKgaUDwHpaGrxRAMOm8UipnYruQcZaiEDoNWexPjZh3b3WAlFit9",
	"Qw2+4KKqsxCniV19DNIRlDs9FPMuAm3AYpq0VqnLTQZk9/4DcqLnGxI/S+ssDNGVmZcWvq7rT79GLRyV",
	"71jCOEYDgZ1/LR+JQ/ss42bI9thZ6MtySN8FkbxmEZSMYHGGG4RRpG3DVC1J16KZ+sVD6aKYjGjdCy2G",
	"G8vbDE8cTTMzmsCjuVm2vWnrYwrdUD/Hugu8PCeqBcIb3k2HgOrao5+D2SUjLBxPTK4JhhdcXIa2r3Xh",
	"6Lzm87PXoJOgTOFNOoRyy4Ir3f1iMJ82UZ5BrI3BNNwDpEDlaCSZxbq/GfhXME/tNMb65onwbSbAvwwG",
	"34+3oC6Pf+sZ7VWdg5bhBIRIBHcS+mjTWbRMBMg71t07UI/WkxrzwlZ7N81fuv9+3/y+frF/BxqGHzWe",
	"V1wzSTF21e7roHjHA4/KF0URCK0wdFbx3u3x+nA5TfV5nhudG8kndgpCuMLwRhi+Q5NJ6pVxjOERuTHj",
	"xSI7Z+jMsLWfODRNMBrrLEMlaAnSaUoOhp+CBjwFqcAi7Rh1EEGrdPj4WywYs7vOj11j+bgR1a9yHIrB",
	"c35+9PI72ycIBsjFAAU/JuX9LwyEbkj0jmCoent4pbvhob8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
