//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorErrorCode.
const (
	Internal            ErrorErrorCode = "internal"
	InvalidRequest      ErrorErrorCode = "invalid_request"
	NoData              ErrorErrorCode = "no_data"
	NotFound            ErrorErrorCode = "not_found"
	UnsupportedCurrency ErrorErrorCode = "unsupported_currency"
	UpstreamUnavailable ErrorErrorCode = "upstream_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case Internal:
		return true
	case InvalidRequest:
		return true
	case NoData:
		return true
	case NotFound:
		return true
	case UnsupportedCurrency:
		return true
	case UpstreamUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusDoneStatus.
const (
	Done JobStatusDoneStatus = "done"
)

// Valid indicates whether the value is a known member of the JobStatusDoneStatus enum.
func (e JobStatusDoneStatus) Valid() bool {
	switch e {
	case Done:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusFailedStatus.
const (
	Failed JobStatusFailedStatus = "failed"
)

// Valid indicates whether the value is a known member of the JobStatusFailedStatus enum.
func (e JobStatusFailedStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusPendingStatus.
const (
	Pending JobStatusPendingStatus = "pending"
)

// Valid indicates whether the value is a known member of the JobStatusPendingStatus enum.
func (e JobStatusPendingStatus) Valid() bool {
	switch e {
	case Pending:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    ErrorErrorCode `json:"code"`
		Message string         `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode defines model for Error.Error.Code.
type ErrorErrorCode string

// JobStatus defines model for JobStatus.
type JobStatus struct {
	union json.RawMessage
}

// JobStatusDone defines model for JobStatusDone.
type JobStatusDone struct {
	Base      string              `json:"base"`
	Id        openapi_types.UUID  `json:"id"`
	Price     float64             `json:"price"`
	Quote     string              `json:"quote"`
	Status    JobStatusDoneStatus `json:"status"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// JobStatusDoneStatus defines model for JobStatusDone.Status.
type JobStatusDoneStatus string

// JobStatusFailed defines model for JobStatusFailed.
type JobStatusFailed struct {
	Base        string                `json:"base"`
	CompletedAt time.Time             `json:"completed_at"`
	Error       string                `json:"error"`
	Id          openapi_types.UUID    `json:"id"`
	Quote       string                `json:"quote"`
	Status      JobStatusFailedStatus `json:"status"`
}

// JobStatusFailedStatus defines model for JobStatusFailed.Status.
type JobStatusFailedStatus string

// JobStatusPending defines model for JobStatusPending.
type JobStatusPending struct {
	Id     openapi_types.UUID     `json:"id"`
	Status JobStatusPendingStatus `json:"status"`
}

// JobStatusPendingStatus defines model for JobStatusPending.Status.
type JobStatusPendingStatus string

// LatestQuote defines model for LatestQuote.
type LatestQuote struct {
	Base      string    `json:"base"`
	Price     float64   `json:"price"`
	Quote     string    `json:"quote"`
	UpdatedAt time.Time `json:"updated_at"`
}

// RefreshAccepted defines model for RefreshAccepted.
type RefreshAccepted struct {
	Id openapi_types.UUID `json:"id"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	Base  string `json:"base"`
	Quote string `json:"quote"`
}

// GetLatestQuoteParams defines parameters for GetLatestQuote.
type GetLatestQuoteParams struct {
	Base        string  `form:"base" json:"base"`
	Quote       string  `form:"quote" json:"quote"`
	XRequestId  *string `json:"X-Request-Id,omitempty"`
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// RefreshQuoteParams defines parameters for RefreshQuote.
type RefreshQuoteParams struct {
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetQuoteJobParams defines parameters for GetQuoteJob.
type GetQuoteJobParams struct {
	XRequestId  *string `json:"X-Request-Id,omitempty"`
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// RefreshQuoteJSONRequestBody defines body for RefreshQuote for application/json ContentType.
type RefreshQuoteJSONRequestBody = RefreshRequest

// AsJobStatusPending returns the union data inside the JobStatus as a JobStatusPending
func (t JobStatus) AsJobStatusPending() (JobStatusPending, error) {
	var body JobStatusPending
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusPending overwrites any union data inside the JobStatus as the provided JobStatusPending
func (t *JobStatus) FromJobStatusPending(v JobStatusPending) error {
	v.Status = "pending"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusPending performs a merge with any union data inside the JobStatus, using the provided JobStatusPending
func (t *JobStatus) MergeJobStatusPending(v JobStatusPending) error {
	v.Status = "pending"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobStatusDone returns the union data inside the JobStatus as a JobStatusDone
func (t JobStatus) AsJobStatusDone() (JobStatusDone, error) {
	var body JobStatusDone
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusDone overwrites any union data inside the JobStatus as the provided JobStatusDone
func (t *JobStatus) FromJobStatusDone(v JobStatusDone) error {
	v.Status = "done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusDone performs a merge with any union data inside the JobStatus, using the provided JobStatusDone
func (t *JobStatus) MergeJobStatusDone(v JobStatusDone) error {
	v.Status = "done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobStatusFailed returns the union data inside the JobStatus as a JobStatusFailed
func (t JobStatus) AsJobStatusFailed() (JobStatusFailed, error) {
	var body JobStatusFailed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobStatusFailed overwrites any union data inside the JobStatus as the provided JobStatusFailed
func (t *JobStatus) FromJobStatusFailed(v JobStatusFailed) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobStatusFailed performs a merge with any union data inside the JobStatus, using the provided JobStatusFailed
func (t *JobStatus) MergeJobStatusFailed(v JobStatusFailed) error {
	v.Status = "failed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JobStatus) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t JobStatus) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "done":
		return t.AsJobStatusDone()
	case "failed":
		return t.AsJobStatusFailed()
	case "pending":
		return t.AsJobStatusPending()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t JobStatus) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JobStatus) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the last successful quote for a currency pair
	// (GET /quotes/latest)
	GetLatestQuote(w http.ResponseWriter, r *http.Request, params GetLatestQuoteParams)
	// Trigger a background currency-rate fetch
	// (POST /quotes/refresh)
	RefreshQuote(w http.ResponseWriter, r *http.Request, params RefreshQuoteParams)
	// Return the state of one refresh job
	// (GET /quotes/{id})
	GetQuoteJob(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetQuoteJobParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLatestQuote operation middleware
func (siw *ServerInterfaceWrapper) GetLatestQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestQuoteParams

	// ------------- Required query parameter "base" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "base", r.URL.Query(), &params.Base, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "base"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "base", Err: err})
		}
		return
	}

	// ------------- Required query parameter "quote" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "quote", r.URL.Query(), &params.Quote, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "quote"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quote", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshQuote operation middleware
func (siw *ServerInterfaceWrapper) RefreshQuote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshQuoteParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshQuote(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuoteJob operation middleware
func (siw *ServerInterfaceWrapper) GetQuoteJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuoteJobParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-Id")]; found {
		var XRequestId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", valueList[0], &XRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-Id", Err: err})
			return
		}

		params.XRequestId = &XRequestId

	}

	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-None-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-None-Match", Err: err})
			return
		}

		params.IfNoneMatch = &IfNoneMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuoteJob(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quotes/latest", wrapper.GetLatestQuote)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/quotes/refresh", wrapper.RefreshQuote)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/quotes/{id}", wrapper.GetQuoteJob)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FnrbhPPFX+VoykSIK0dkwTUmk8hpCgRhDQQiRbSaDxz1p50d2YzlwQrstSH6BP2Saozu+u1vY7t0AAS",
	"f/hAVjtnzu13rutbJkxeGI3aO9a/ZU6MMOfx8cBaY+mhsKZA6xXG17j8tTAS47EOOet/Zkpf80zJC4tX",
	"AZ1nCQvahaIw1qO8EMFa1GLMEqbNheSexyd/kZqgJREXzlvk+UXQ/JqrjA8yZAlT2qPVPGPnCfPjAlmf",
	"OW+VHrJJwnJ0jg9LLb7yvMjouJYEj49O/v4YlANtPEw1YS0+k4SRzsqiJDuiXQ3vRq4ZXKLwLfrSPW2y",
	"hB2ZwQfPfYjuksoJq3KluS+9mfOiIPl0ZjTd/NNWA81WhcvWlMlrIkpYylVGgtdQ/7UkS1iBWkYxay6c",
	"VHSTpMZ5fMzz0k/RhknCjMb3Ket/vmWPLKb3YLnhhWjixtSViZPzWVdHFq1YHXAX37YiSEl6nRqbc8/6",
	"LAS1JEDII0rgHKU0oQzQilaHfICWaK+C8cuFuWkw1DkTgV8W2aGQnNKGZM1K5R47XuW4NoqjHdHsWqOp",
	"/NqcOSkr47fy9OZuJdgyvJ8BSVNovhWm+7i+yqPz/8uRc3Ymm5SCOidavtzQxLYhdYJvZkl1f5mOb7lH",
	"5/9W+3A51E2dPTg7XZkqU8rtXnf7+fMXu39O7pU+jaR3n47Z98iRBVQ3zIpTTC260Z4QWPhlWVEi2aj/",
	"l8ELfJbu8E6v1+st/Ff/Y8k66NtgrlDutOrBG8NYcE99lvXZPz/vdf5xfrszebQywxbR2YzBKgCWNFrK",
	"fJ2a2CKR2mfhlSEZe26sxcgabYKDacOPfMChvVYCu7CfKWoc4K0aDtECB1t6B64V/6JP3n/4CFvxjtuq",
	"ThIoTJZBaiz4EYJFFzJP5PDmoCG+VXKSANfyi7bIZSTNYvKA4GKEstJk8V5J0/2iyTHKR+/t18rHvIMP",
	"pfIsYddoXWlsr/us24vtt0DNC8X6bKfb6+6UXh9FXOdF0Jshxj8EPievHdLM8Ab9bJYTA8tz9GhdbOuK",
	"5F0FtHFOK9t/BVKDm7cBk2pujBG2IfTL2dfZ92D8R8gl2kbAp06VDZ3DWACnfDdlcJh2jo3GzjvuxWgl",
	"h3MywxVGuzLbtnu9clLWHnWEgxdFpkQEZOvSEby3M/xWjT2zuMXMmM+I8hhcEAKdS0NWxWATytEHKKHg",
	"ynZZUpkZ9dynqO3sG+2tydrZdhIGmRIxtpUeglQWhVfXCDfKjyDnXzt8iIBXgWfgDQjDM3SCSG+Uluam",
	"u9rt7OAjH7alHmiv/Bg8H0YjhNFS0RHPYlJVA/063nPozzl7kZaod3q7bUWOjYd3RqpUoYT//vs/QPpC",
	"TtGA8iVoAwMjx2DRB6tRLvh2I+MIoap0WHQmWIEPa9juA0ZiuSYuicFXXNZxFv00s/9Ni3QC1Z4IZb9L",
	"wFhwmKWdTeLyIR2y+/0dcmzaCYlflfMOxugr5JWDH2v68x8RC4fV3h7bMVqIo/GPspHm5JDn3I5Zn53G",
	"vKya9F0lkjdTBIERJS7MBrEVGbekq1ZD16qe+s1N6bzsjOj8KyPHD4bbwpw4mZ/MqANPWr1s+6GlT0fo",
	"JfFzZAbAq3MatUAGywfZGFBfBQytMrumhcXjmc41M+FFE9dV27emNLTN+ez0LZg0MtN4k41BWKT1AS7N",
	"4JuL+byI6gyEsRazqAcoidpTS7Kref+04l+XeUqnaa1f3hF+Tgf4g5XBj9MtaMDFv4bWBN1g0LGcCiHS",
	"gDtb+mjTWbVMxJJ3ZAZ3VD1aT5qaF7fau8f8tfvvrz3fNx+L76iG8UP5y3rWTDMUvt59PZSfdeBJ9TEo",
	"AWk0xswqv3M9vX+5nB/1eVFYU1jFZ3YKqnCl4AeZ8D3aXFGuTH0MT8iMBStWyTlFb8edvdSjXVZGhclz",
	"1JKWIJNlZGD8eeGaZ6A0OKQdo3EiGJ2Nn/6MBWNx1/m9a6xvN7L+pYdD2XjOzg5f/2L7BJUBMjGWgt+d",
	"8vsvDFTdkMY7KkP118NLM4iX/hcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
